title: Failsafe-go
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://failsafe-go.dev" # the base hostname & protocol for your site, e.g. http://example.com
github-url: https://github.com/failsafe-go/failsafe-go
web-github-url: https://github.com/failsafe-go/failsafe-go.github.io
permalink: pretty
safe: true
exclude:
  - Gemfile*
  - bin
  - vendor
  - Rakefile
  - README.md
markdown: kramdown
highlighter: none
search_enabled: true

# aux_links:
#   "View on GitHub":
#     - "//github.com/failsafe-go/failsafe-go"

ga_tracking: G-69HPC64MH7

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false